// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Auction struct {
	ID        int32        `json:"id"`
	IDShop    int32        `json:"id_shop"`
	Closure   sql.NullTime `json:"closure"`
	CreatedAd time.Time    `json:"created_ad"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Award struct {
	ID        int32     `json:"id"`
	AwardTime int32     `json:"award_time"`
	IDItems   int32     `json:"id_items"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type BanComment struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type BanForum struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Block struct {
	ID             int32     `json:"id"`
	IDUser         int32     `json:"id_user"`
	IDBlockingTime int32     `json:"id_blocking_time"`
	CreatedAd      time.Time `json:"created_ad"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type BlockingTime struct {
	ID        int32     `json:"id"`
	Time      int32     `json:"time"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Boss struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Level     int32     `json:"level"`
	IDMaps    int32     `json:"id_maps"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Character struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Name      string    `json:"name"`
	ClassID   int32     `json:"class_id"`
	Level     int32     `json:"level"`
	Main      bool      `json:"main"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Class struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID           int32     `json:"id"`
	IDUser       int32     `json:"id_user"`
	IDForum      int32     `json:"id_forum"`
	Content      string    `json:"content"`
	IDBanComment int32     `json:"id_ban_comment"`
	CreatedAd    time.Time `json:"created_ad"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type EditedText struct {
	ID               int32     `json:"id"`
	IDUserEdited     int32     `json:"id_user_edited"`
	IDMigration      int32     `json:"id_migration"`
	Content          string    `json:"content"`
	IDTypeEditedText int32     `json:"id_type_edited_text"`
	CreatedAd        time.Time `json:"created_ad"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Forum struct {
	ID            int32     `json:"id"`
	IDUser        int32     `json:"id_user"`
	IDCategory    int32     `json:"id_category"`
	Title         string    `json:"title"`
	Content       string    `json:"content"`
	IDStatusForum int32     `json:"id_status_forum"`
	IDBanForum    int32     `json:"id_ban_forum"`
	CreatedAd     time.Time `json:"created_ad"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type InformationUserVote struct {
	ID             int32          `json:"id"`
	IDUser         int32          `json:"id_user"`
	OldClan        sql.NullString `json:"old_clan"`
	ReasonExit     sql.NullString `json:"reason_exit"`
	Friend         sql.NullString `json:"friend"`
	PlaySod        bool           `json:"play_sod"`
	PlayBc         bool           `json:"play_bc"`
	AvailabilityBc bool           `json:"availability_bc"`
	Description    sql.NullString `json:"description"`
	CreatedAd      time.Time      `json:"created_ad"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Integration struct {
	ID                int32         `json:"id"`
	IDUser            int32         `json:"id_user"`
	IDMigration       int32         `json:"id_migration"`
	IDUserPush        sql.NullInt32 `json:"id_user_push"`
	IDTypeIntegration int32         `json:"id_type_integration"`
	CreatedAd         time.Time     `json:"created_ad"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type Item struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	Level       int32           `json:"level"`
	IDTypeItems int32           `json:"id_type_items"`
	Description json.RawMessage `json:"description"`
	CreatedAd   time.Time       `json:"created_ad"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ItemsSale struct {
	ID          int32           `json:"id"`
	IDItems     int32           `json:"id_items"`
	Description json.RawMessage `json:"description"`
	CreatedAd   time.Time       `json:"created_ad"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Level struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type LevelUser struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	LevelID   int32     `json:"level_id"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ListStatusVote struct {
	ID           int32     `json:"id"`
	IDStatusVote int32     `json:"id_status_vote"`
	CreatedAd    time.Time `json:"created_ad"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Map struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Level     int32     `json:"level"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Member struct {
	ID           int32     `json:"id"`
	IDParty      int32     `json:"id_party"`
	IDCharacters int32     `json:"id_characters"`
	CreatedAd    time.Time `json:"created_ad"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Notification struct {
	ID                  int32         `json:"id"`
	IDUser              int32         `json:"id_user"`
	IDMigration         int32         `json:"id_migration"`
	IDUserPush          sql.NullInt32 `json:"id_user_push"`
	IDTypeNotifications int32         `json:"id_type_notifications"`
	CreatedAd           time.Time     `json:"created_ad"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type NotificationsSystem struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Party struct {
	ID            int32     `json:"id"`
	IDUser        int32     `json:"id_user"`
	IDTypeParty   int32     `json:"id_type_party"`
	IDLeaderParty int32     `json:"id_leader_party"`
	IDMap         int32     `json:"id_map"`
	IDSubServer   int32     `json:"id_sub_server"`
	Time          time.Time `json:"time"`
	CreatedAd     time.Time `json:"created_ad"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Password struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Password  string    `json:"password"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Photo struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Photo     string    `json:"photo"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Ranking struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Amount    string    `json:"amount"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ScoreRankingUser struct {
	ID          int32     `json:"id"`
	IDUser      int32     `json:"id_user"`
	IDTypeScore int32     `json:"id_type_score"`
	IDMigration int32     `json:"id_migration"`
	Amount      string    `json:"amount"`
	CreatedAd   time.Time `json:"created_ad"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Setting struct {
	ID                          int32     `json:"id"`
	Nome                        string    `json:"nome"`
	VoteAnalysisTime            int32     `json:"vote_analysis_time"`
	RecruitmentMinimumLevel     int32     `json:"recruitment_minimum_level"`
	RecruitmentMaximumLevel     int32     `json:"recruitment_maximum_level"`
	Soon                        string    `json:"soon"`
	RecruitmentAlert            string    `json:"recruitment_alert"`
	IDLevelRecruiter            int32     `json:"id_level_recruiter"`
	IDLevelGeneralConfiguration int32     `json:"id_level_general_configuration"`
	CreatedAd                   time.Time `json:"created_ad"`
	UpdatedAt                   time.Time `json:"updated_at"`
}

type Shop struct {
	ID          int32     `json:"id"`
	IDUser      int32     `json:"id_user"`
	IDItemsSale int32     `json:"id_items_sale"`
	Value       string    `json:"value"`
	Content     string    `json:"content"`
	IDTypeSale  int32     `json:"id_type_sale"`
	CreatedAd   time.Time `json:"created_ad"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Signature struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Content   string    `json:"content"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Status struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StatusForum struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StatusUser struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	IDStatus  int32     `json:"id_status"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StatusVote struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SubServer struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Pvp       int32     `json:"pvp"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Throw struct {
	ID        int32     `json:"id"`
	IDAuction int32     `json:"id_auction"`
	IDUser    int32     `json:"id_user"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TimeBoss struct {
	ID        int32     `json:"id"`
	IDBoss    int32     `json:"id_boss"`
	Time      time.Time `json:"time"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TimeServer struct {
	ID          int32     `json:"id"`
	IDSubServer int32     `json:"id_sub_server"`
	Time        time.Time `json:"time"`
	CreatedAd   time.Time `json:"created_ad"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TypeEditedText struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeIntegration struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeItem struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeNotification struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeParty struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeSale struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeScore struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeVote struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TypeVow struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Telephone string    `json:"telephone"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Vote struct {
	ID               int32     `json:"id"`
	IDUser           int32     `json:"id_user"`
	IDListStatusVote int32     `json:"id_list_status_vote"`
	IDTypeVote       int32     `json:"id_type_vote"`
	CreatedAd        time.Time `json:"created_ad"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type VotingOption struct {
	ID        int32          `json:"id"`
	IDVote    int32          `json:"id_vote"`
	Text      sql.NullString `json:"text"`
	Photo     sql.NullString `json:"photo"`
	CreatedAd time.Time      `json:"created_ad"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Vow struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	IDVote    int32     `json:"id_vote"`
	IDTypeVow int32     `json:"id_type_vow"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Winner struct {
	ID        int32     `json:"id"`
	IDUser    int32     `json:"id_user"`
	Amount    string    `json:"amount"`
	IDAward   int32     `json:"id_award"`
	CreatedAd time.Time `json:"created_ad"`
	UpdatedAt time.Time `json:"updated_at"`
}
