// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AssignStatus(ctx context.Context, arg AssignStatusParams) (StatusUser, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	CreateClass(ctx context.Context, name string) (Class, error)
	CreateLevel(ctx context.Context, name string) (Level, error)
	CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error)
	CreateStatus(ctx context.Context, name string) (Status, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetClass(ctx context.Context) ([]Class, error)
	GetInformationUserVote(ctx context.Context, idUser int32) (InformationUserVote, error)
	GetLevel(ctx context.Context) ([]Level, error)
	GetLoginByEmail(ctx context.Context, email string) (GetLoginByEmailRow, error)
	GetMainCharacter(ctx context.Context, arg GetMainCharacterParams) (Character, error)
	GetStatus(ctx context.Context) ([]Status, error)
	GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error)
	InformationUserVote(ctx context.Context, arg InformationUserVoteParams) (InformationUserVote, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateMainCharacter(ctx context.Context, arg UpdateMainCharacterParams) (Character, error)
}

var _ Querier = (*Queries)(nil)
